tweak my reminders script

diff --git a/utils/mutt b/utils/mutt
--- a/utils/mutt
+++ b/utils/mutt
@@ -4,10 +4,14 @@ set -e
 
 # Check for flashcards and any reminders before checking email.
 flashcard
-firstrem="$(head -c 10 ~/rems)"
+firstrem="$(sort ~/.rems | sed '/^$/d' | head -c 10)"
+if ! [[ "$firstrem" =~ ^20[0-9][0-9]-[0-9][0-9]-[0-9][0-9]$ ]]; then
+  echo "Error in the ~/.rems file."
+  exit 1
+fi
 curdate="$(date +%Y-%m-%d)"
 if test "$curdate" '<' "$firstrem"; then
   /usr/bin/mutt "$@"
 else
-  echo "Please take care of the reminders first in ~/rems."
-fi;
+  echo "Please take care of the reminders first in ~/.rems."
+fi
